// Code generated by cdpgen. DO NOT EDIT.

package database

import (
	"encoding/json"
)

// GetDatabaseTableNamesArgs represents the arguments for GetDatabaseTableNames in the Database domain.
type GetDatabaseTableNamesArgs struct {
	DatabaseID ID `json:"databaseId"` //
}

// NewGetDatabaseTableNamesArgs initializes GetDatabaseTableNamesArgs with the required arguments.
func NewGetDatabaseTableNamesArgs(databaseID ID) *GetDatabaseTableNamesArgs {
	args := new(GetDatabaseTableNamesArgs)
	args.DatabaseID = databaseID
	return args
}

// GetDatabaseTableNamesReply represents the return values for GetDatabaseTableNames in the Database domain.
type GetDatabaseTableNamesReply struct {
	TableNames []string `json:"tableNames"` //
}

// ExecuteSQLArgs represents the arguments for ExecuteSQL in the Database domain.
type ExecuteSQLArgs struct {
	DatabaseID ID     `json:"databaseId"` //
	Query      string `json:"query"`      //
}

// NewExecuteSQLArgs initializes ExecuteSQLArgs with the required arguments.
func NewExecuteSQLArgs(databaseID ID, query string) *ExecuteSQLArgs {
	args := new(ExecuteSQLArgs)
	args.DatabaseID = databaseID
	args.Query = query
	return args
}

// ExecuteSQLReply represents the return values for ExecuteSQL in the Database domain.
type ExecuteSQLReply struct {
	ColumnNames []string          `json:"columnNames,omitempty"` //
	Values      []json.RawMessage `json:"values,omitempty"`      //
	SQLError    *Error            `json:"sqlError,omitempty"`    //
}
