// Code generated by cdpgen. DO NOT EDIT.

package console

import (
	"github.com/mafredri/cdp/rpcc"
)

// MessageAddedClient is a client for MessageAdded events. Issued when new console message is added.
type MessageAddedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*MessageAddedReply, error)
	rpcc.Stream
}

// MessageAddedReply is the reply for MessageAdded events.
type MessageAddedReply struct {
	Message Message `json:"message"` // Console message that has been added.
}
