language: go

sudo: false

addons:
  chrome: stable

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - master

before_install:
  # Use --disable-setuid-sandbox to avoid core dump on Travis.
  # And --no-sandbox (https://github.com/travis-ci/travis-ci/issues/8836).
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 --disable-setuid-sandbox --no-sandbox about:blank &

script:
  - go list -f '{{if len .TestGoFiles}}-coverprofile={{.Name}}_coverage.out {{.ImportPath}}{{end}}' ./... | xargs -L1 go test -race -covermode=atomic
  - go test ./session -browser -race -covermode=atomic -coverprofile=session_coverage.out
  - go test . -browser

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - killall google-chrome-stable

matrix:
  fast_finish: true
  allow_failures:
    - go: master
