language: go

go:
  - 1.8.x
  - tip

script:
  - go list -f '{{if len .TestGoFiles}}-coverprofile={{.Name}}_coverage.out {{.ImportPath}}{{end}}' ./... | xargs -L1 go test -race -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true
