// Code generated by cdpgen. DO NOT EDIT.

package heapprofiler

import (
	"github.com/mafredri/cdp/protocol/runtime"
)

// HeapSnapshotObjectID Heap snapshot object id.
type HeapSnapshotObjectID string

// SamplingHeapProfileNode Sampling Heap Profile node. Holds callsite information, allocation statistics and child nodes.
type SamplingHeapProfileNode struct {
	CallFrame runtime.CallFrame         `json:"callFrame"` // Function location.
	SelfSize  float64                   `json:"selfSize"`  // Allocations size in bytes for the node excluding children.
	Children  []SamplingHeapProfileNode `json:"children"`  // Child nodes.
}

// SamplingHeapProfile Profile.
type SamplingHeapProfile struct {
	Head SamplingHeapProfileNode `json:"head"` // No description.
}
