// Code generated by cdpgen. DO NOT EDIT.

package systeminfo

// GetInfoReply represents the return values for GetInfo in the SystemInfo domain.
type GetInfoReply struct {
	GPU          GPUInfo `json:"gpu"`          // Information about the GPUs on the system.
	ModelName    string  `json:"modelName"`    // A platform-dependent description of the model of the machine. On Mac OS, this is, for example, 'MacBookPro'. Will be the empty string if not supported.
	ModelVersion string  `json:"modelVersion"` // A platform-dependent description of the version of the machine. On Mac OS, this is, for example, '10.1'. Will be the empty string if not supported.
	CommandLine  string  `json:"commandLine"`  // The command line string used to launch the browser. Will be the empty string if not supported.
}

// GetFeatureStateArgs represents the arguments for GetFeatureState in the SystemInfo domain.
type GetFeatureStateArgs struct {
	FeatureState string `json:"featureState"` // No description.
}

// NewGetFeatureStateArgs initializes GetFeatureStateArgs with the required arguments.
func NewGetFeatureStateArgs(featureState string) *GetFeatureStateArgs {
	args := new(GetFeatureStateArgs)
	args.FeatureState = featureState
	return args
}

// GetFeatureStateReply represents the return values for GetFeatureState in the SystemInfo domain.
type GetFeatureStateReply struct {
	FeatureEnabled bool `json:"featureEnabled"` // No description.
}

// GetProcessInfoReply represents the return values for GetProcessInfo in the SystemInfo domain.
type GetProcessInfoReply struct {
	ProcessInfo []ProcessInfo `json:"processInfo"` // An array of process info blocks.
}
