// Code generated by cdpgen. DO NOT EDIT.

package autofill

import (
	"github.com/mafredri/cdp/protocol/dom"
	"github.com/mafredri/cdp/protocol/page"
)

// TriggerArgs represents the arguments for Trigger in the Autofill domain.
type TriggerArgs struct {
	FieldID dom.BackendNodeID `json:"fieldId"`           // Identifies a field that serves as an anchor for autofill.
	FrameID *page.FrameID     `json:"frameId,omitempty"` // Identifies the frame that field belongs to.
	Card    CreditCard        `json:"card"`              // Credit card information to fill out the form. Credit card data is not saved.
}

// NewTriggerArgs initializes TriggerArgs with the required arguments.
func NewTriggerArgs(fieldID dom.BackendNodeID, card CreditCard) *TriggerArgs {
	args := new(TriggerArgs)
	args.FieldID = fieldID
	args.Card = card
	return args
}

// SetFrameID sets the FrameID optional argument. Identifies the frame
// that field belongs to.
func (a *TriggerArgs) SetFrameID(frameID page.FrameID) *TriggerArgs {
	a.FrameID = &frameID
	return a
}

// SetAddressesArgs represents the arguments for SetAddresses in the Autofill domain.
type SetAddressesArgs struct {
	Addresses []Address `json:"addresses"` // No description.
}

// NewSetAddressesArgs initializes SetAddressesArgs with the required arguments.
func NewSetAddressesArgs(addresses []Address) *SetAddressesArgs {
	args := new(SetAddressesArgs)
	args.Addresses = addresses
	return args
}
