// Code generated by cdpgen. DO NOT EDIT.

package fedcm

import (
	"github.com/mafredri/cdp/rpcc"
)

// DialogShownClient is a client for DialogShown events.
type DialogShownClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*DialogShownReply, error)
	rpcc.Stream
}

// DialogShownReply is the reply for DialogShown events.
type DialogShownReply struct {
	DialogID   string     `json:"dialogId"`           // No description.
	DialogType DialogType `json:"dialogType"`         // No description.
	Accounts   []Account  `json:"accounts"`           // No description.
	Title      string     `json:"title"`              // These exist primarily so that the caller can verify the RP context was used appropriately.
	Subtitle   *string    `json:"subtitle,omitempty"` // No description.
}

// DialogClosedClient is a client for DialogClosed events. Triggered when a
// dialog is closed, either by user action, JS abort, or a command below.
type DialogClosedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*DialogClosedReply, error)
	rpcc.Stream
}

// DialogClosedReply is the reply for DialogClosed events.
type DialogClosedReply struct {
	DialogID string `json:"dialogId"` // No description.
}
