// Code generated by cdpgen. DO NOT EDIT.

package applicationcache

import (
	"github.com/mafredri/cdp/rpcc"
)

// StatusUpdatedClient is a client for ApplicationCacheStatusUpdated events.
type StatusUpdatedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*StatusUpdatedReply, error)
	rpcc.Stream
}

// NetworkStateUpdatedReply is the reply for NetworkStateUpdated events.
type NetworkStateUpdatedReply struct {
	IsNowOnline bool `json:"isNowOnline"` // No description.
}
